#! /bin/bash
#$ -cwd
#$ -q JM,UI
#$ -pe smp 24
#$ -N surfboard-acoustics
#$ -o logs/$JOB_NAME.log
#$ -j y
#$ -ckpt user


conda activate surfboard
SURF=/Dedicated/jmichaelson-wdata/msmuhammad/workbench/surfboard/example_configs/parkinsons_features.yaml
PROJECT_DIR=/Dedicated/jmichaelson-wdata/msmuhammad/projects/RPOE/language
OUT_DIR=$PROJECT_DIR/data/derivatives/surfboard_out
mkdir -p $OUT_DIR/surfboard_in

cp -R $PROJECT_DIR/data/derivatives/PS-VC_participants-response/*/*task-2* $OUT_DIR/surfboard_in/

surfboard compute-features -i $OUT_DIR/surfboard_in -o $OUT_DIR/ALL_task-2.csv -F $SURF -j 20

